name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  unit-php:
    name: PHP Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: pcov

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.json') }}
          restore-keys: composer-

      - name: Install Composer dependencies
        run: composer install --dev --prefer-dist --no-progress

      - name: Run Pest
        run: ./vendor/bin/pest --colors=always --coverage --min=50
